// host/src/App.vue
<template>
  <div style="font-family: system-ui, Arial; padding: 24px">
    <h1>Vue MFE — Host App</h1>
    <p>
      This will be the host application that integrates React and Vue remotes
      later.
    </p>
    <p>Origin: <code>http://localhost:3002</code></p>
  </div>
</template>

<script setup>
// No logic yet — we’ll add Module Federation setup later
</script>

<style>
body {
  margin: 0;
  background-color: #454141;
}
</style>

// react/src/App.jsx
function App() {
  return (
    <div style={{ fontFamily: "system-ui, Arial", padding: 24 }}>
      <h1>React MFE — react1</h1>
      <p>This is a basic React app for learning Module Federation.</p>
      <p>
        Origin: <code>http://localhost:3000</code>
      </p>
    </div>
  );
}

export default App;
