// react/src/App.jsx
function App() {
  return (
    <div style={{ fontFamily: "system-ui, Arial", padding: 24 }}>
      <h1>React MFE — react1</h1>
      <p>This is a basic React app for learning Module Federation.</p>
      <p>
        Origin: <code>http://localhost:3000</code>
      </p>
    </div>
  );
}

export default App;

// vue/src/App.vue
<template>
  <div style="font-family: system-ui, Arial; padding: 24px">
    <h1>Vue MFE — vue1</h1>
    <p>This is a basic Vue 3 app for learning Module Federation.</p>
    <p>Origin: <code>http://localhost:3001</code></p>
  </div>
</template>

<script setup>
// no logic yet — just a basic app
</script>

<style>
body {
  margin: 0;
  background-color: #f5f5f5;
}
</style>
